import type { HeroSlide, MenuItem, Program, News, Member, Transaction, Notification, EventRegistration, AgendaEvent, KajianSession } from './types'

// Hero Slides Data
export const heroSlides: HeroSlide[] = [
  {
    id: 1,
    title: "Ramadhan Kareem",
    subtitle: "Selamat Menjalankan Ibadah Puasa",
    description: "Semoga amal ibadah kita diterima Allah SWT",
    gradient: "from-red-600 via-red-500 to-rose-500",
  },
  {
    id: 2,
    title: "Kajian Rutin",
    subtitle: "Setiap Sabtu & Ahad",
    description: "Bersama Ustadz Ahmad Sulaiman",
    gradient: "from-rose-600 via-red-500 to-orange-500",
  },
  {
    id: 3,
    title: "Sedekah Jariyah",
    subtitle: "Ayo Berbagi Kebaikan",
    description: "Sedekah tidak akan mengurangi harta",
    gradient: "from-amber-600 via-red-500 to-rose-500",
  },
]

// Menu Icons Data
export const menuItems: MenuItem[] = [
  { id: "kajian", label: "Kajian", icon: "BookOpen", color: "bg-red-500" },
  { id: "agenda", label: "Agenda", icon: "Calendar", color: "bg-rose-500" },
  { id: "biro-jodoh", label: "Biro Jodoh", icon: "Heart", color: "bg-pink-500" },
  { id: "informasi", label: "Informasi", icon: "Info", color: "bg-amber-500" },
  { id: "sedekah", label: "Sedekah", icon: "HandHeart", color: "bg-orange-500" },
  { id: "lainnya", label: "Lainnya", icon: "MoreHorizontal", color: "bg-gray-500" },
]

// Program Pendidikan Data
export const programData: Program[] = [
  {
    id: 1,
    title: "TPA (Taman Pendidikan Al-Quran)",
    description: "Pendidikan baca tulis Al-Quran untuk anak-anak",
    level: "Usia 5-12 Tahun",
    schedule: "Senin - Jumat, 15:00 - 17:00",
    icon: "GraduationCap",
    color: "bg-red-500",
    registered: 45,
    capacity: 50,
  },
  {
    id: 2,
    title: "Madrasah Diniyah",
    description: "Pembelajaran ilmu agama Islam secara mendalam",
    level: "Remaja & Dewasa",
    schedule: "Sabtu & Ahad, 08:00 - 11:00",
    icon: "BookOpen",
    color: "bg-rose-500",
    registered: 32,
    capacity: 40,
  },
  {
    id: 3,
    title: "Tahsin Al-Quran",
    description: "Perbaikan bacaan Al-Quran dengan tajwid yang benar",
    level: "Semua Usia",
    schedule: "Senin & Kamis, 19:00 - 20:30",
    icon: "Star",
    color: "bg-amber-500",
    registered: 28,
    capacity: 30,
  },
  {
    id: 4,
    title: "Fiqih Praktis",
    description: "Pembelajaran hukum Islam dalam kehidupan sehari-hari",
    level: "Remaja & Dewasa",
    schedule: "Selasa, 19:00 - 20:30",
    icon: "BookOpen",
    color: "bg-orange-500",
    registered: 18,
    capacity: 25,
  },
]

// News Data
export const newsData: News[] = [
  {
    id: 1,
    title: "Peringatan Maulid Nabi Muhammad SAW 1446 H",
    excerpt: "Mari bergabung dalam peringatan Maulid Nabi yang akan diselenggarakan pada tanggal 15 September 2024 di Aula Utama Yayasan Mufid.",
    date: "12 September 2024",
    category: "Acara",
    image: "bg-gradient-to-br from-red-500/20 to-rose-500/5",
    readTime: "3 menit",
  },
  {
    id: 2,
    title: "Jadwal Imam Tarawih Ramadhan 1446 H",
    excerpt: "Berikut jadwal imam tarawih yang akan memimpin sholat tarawih selama bulan Ramadhan 1446 H.",
    date: "10 September 2024",
    category: "Pengumuman",
    image: "bg-gradient-to-br from-rose-500/20 to-orange-500/5",
    readTime: "2 menit",
  },
  {
    id: 3,
    title: "Peluncuran Program Beasiswa Yatim Piatu",
    excerpt: "Yayasan Mufid dengan bangga meluncurkan program beasiswa untuk anak yatim piatu di wilayah sekitar.",
    date: "8 September 2024",
    category: "Program",
    image: "bg-gradient-to-br from-amber-500/20 to-orange-500/5",
    readTime: "4 menit",
  },
  {
    id: 4,
    title: "Kajian Kitab Riyadhus Shalihin Dimulai",
    excerpt: "Kajian rutin kitab Riyadhus Shalihin bersama Ustadz Ahmad akan dimulai minggu depan.",
    date: "5 September 2024",
    category: "Kajian",
    image: "bg-gradient-to-br from-orange-500/20 to-red-500/5",
    readTime: "3 menit",
  },
]

// Members Data (for Data page)
export const membersData: Member[] = [
  {
    id: "M001",
    name: "Ahmad Fauzi",
    email: "ahmad.fauzi@email.com",
    phone: "081234567890",
    program: "TPA (Taman Pendidikan Al-Quran)",
    registerDate: "01 September 2024",
    status: "active",
    avatar: "",
  },
  {
    id: "M002",
    name: "Siti Aisyah",
    email: "siti.aisyah@email.com",
    phone: "081234567891",
    program: "Madrasah Diniyah",
    registerDate: "03 September 2024",
    status: "active",
  },
  {
    id: "M003",
    name: "Muhammad Rizki",
    email: "muhammad.rizki@email.com",
    phone: "081234567892",
    program: "Tahsin Al-Quran",
    registerDate: "05 September 2024",
    status: "pending",
  },
  {
    id: "M004",
    name: "Fatimah Zahra",
    email: "fatimah.zahra@email.com",
    phone: "081234567893",
    program: "Fiqih Praktis",
    registerDate: "07 September 2024",
    status: "active",
  },
  {
    id: "M005",
    name: "Umar Hadi",
    email: "umar.hadi@email.com",
    phone: "081234567894",
    program: "TPA (Taman Pendidikan Al-Quran)",
    registerDate: "08 September 2024",
    status: "active",
  },
  {
    id: "M006",
    name: "Khadijah Nur",
    email: "khadijah.nur@email.com",
    phone: "081234567895",
    program: "Madrasah Diniyah",
    registerDate: "10 September 2024",
    status: "inactive",
  },
  {
    id: "M007",
    name: "Ibrahim Hasan",
    email: "ibrahim.hasan@email.com",
    phone: "081234567896",
    program: "Tahsin Al-Quran",
    registerDate: "11 September 2024",
    status: "active",
  },
  {
    id: "M008",
    name: "Zainab Putri",
    email: "zainab.putri@email.com",
    phone: "081234567897",
    program: "Fiqih Praktis",
    registerDate: "12 September 2024",
    status: "pending",
  },
]

// Transactions Data (for Riwayat page)
export const transactionsData: Transaction[] = [
  {
    id: "TRX001",
    type: "donation",
    title: "Sedekah Jariyah",
    amount: 500000,
    date: "15 September 2024",
    status: "success",
    description: "Donasi untuk pembangunan masjid",
  },
  {
    id: "TRX002",
    type: "registration",
    title: "Pendaftaran TPA",
    amount: 150000,
    date: "14 September 2024",
    status: "success",
    description: "Biaya pendaftaran program TPA",
  },
  {
    id: "TRX003",
    type: "event",
    title: "Iftar Jama'i",
    amount: 75000,
    date: "13 September 2024",
    status: "success",
    description: "Kontribusi buka puasa bersama",
  },
  {
    id: "TRX004",
    type: "donation",
    title: "Wakaf Al-Quran",
    amount: 250000,
    date: "12 September 2024",
    status: "pending",
    description: "Wakaf mushaf Al-Quran",
  },
  {
    id: "TRX005",
    type: "payment",
    title: "SPP Madrasah",
    amount: 200000,
    date: "10 September 2024",
    status: "success",
    description: "SPP bulan September 2024",
  },
  {
    id: "TRX006",
    type: "donation",
    title: "Infaq Jumat",
    amount: 100000,
    date: "08 September 2024",
    status: "success",
    description: "Infaq sholat Jumat",
  },
]

// Notifications Data (for Riwayat page)
export const notificationsData: Notification[] = [
  {
    id: "N001",
    title: "Pendaftaran Berhasil",
    message: "Selamat! Pendaftaran program TPA Anda telah dikonfirmasi.",
    type: "success",
    date: "15 September 2024",
    read: false,
  },
  {
    id: "N002",
    title: "Pengingat Kajian",
    message: "Jangan lupa menghadiri kajian rutin malam ini pukul 19:00 WIB.",
    type: "info",
    date: "14 September 2024",
    read: false,
  },
  {
    id: "N003",
    title: "Pembayaran Tertunda",
    message: "Pembayaran sedekah jariyah Anda sedang dalam proses verifikasi.",
    type: "warning",
    date: "12 September 2024",
    read: true,
  },
  {
    id: "N004",
    title: "Event Baru",
    message: "Event Maulid Nabi telah ditambahkan, segera daftarkan diri Anda!",
    type: "info",
    date: "10 September 2024",
    read: true,
  },
]

// Event Registrations Data (for Riwayat page)
export const eventRegistrationsData: EventRegistration[] = [
  {
    id: "E001",
    eventName: "Maulid Nabi Muhammad SAW 1446 H",
    eventDate: "15 September 2024",
    registerDate: "12 September 2024",
    status: "registered",
    location: "Aula Utama Yayasan Mufid",
  },
  {
    id: "E002",
    eventName: "Iftar Jama'i Ramadhan",
    eventDate: "20 Maret 2024",
    registerDate: "18 Maret 2024",
    status: "attended",
    location: "Masjid Al-Ikhlas",
  },
  {
    id: "E003",
    eventName: "Seminar Parenting Islami",
    eventDate: "25 Agustus 2024",
    registerDate: "20 Agustus 2024",
    status: "attended",
    location: "Gedung Serbaguna Mufid",
  },
  {
    id: "E004",
    eventName: "Qurban Idul Adha",
    eventDate: "10 Juli 2024",
    registerDate: "01 Juli 2024",
    status: "attended",
    location: "Lapangan Yayasan Mufid",
  },
]

// Agenda Events Data
export const agendaEventsData: AgendaEvent[] = [
  {
    id: "AG001",
    title: "Kajian Rutin Malam Jumat",
    description: "Kajian kitab Riyadhus Shalihin bersama Ustadz Ahmad Sulaiman",
    date: "2024-09-20",
    time: "19:30 - 21:00 WIB",
    location: "Masjid Utama Mufid",
    category: "kajian",
    speaker: "Ustadz Ahmad Sulaiman",
    isHighlight: true,
  },
  {
    id: "AG002",
    title: "Pengajian Ibu-Ibu",
    description: "Pengajian rutin bulanan untuk ibu-ibu dengan tema mendidik anak dalam Islam",
    date: "2024-09-21",
    time: "09:00 - 11:00 WIB",
    location: "Aula Serbaguna",
    category: "pengajian",
    speaker: "Ustadzah Fatimah",
  },
  {
    id: "AG003",
    title: "Maulid Nabi Muhammad SAW",
    description: "Peringatan Maulid Nabi Muhammad SAW 1446 H dengan berbagai acara",
    date: "2024-09-15",
    time: "07:00 - 12:00 WIB",
    location: "Lapangan Utama Yayasan Mufid",
    category: "event",
    isHighlight: true,
  },
  {
    id: "AG004",
    title: "Rapat Koordinasi Pengurus",
    description: "Rapat bulanan pengurus yayasan membahas program kegiatan",
    date: "2024-09-22",
    time: "14:00 - 16:00 WIB",
    location: "Ruang Rapat Lt. 2",
    category: "rapat",
  },
  {
    id: "AG005",
    title: "Kajian Fiqih Wanita",
    description: "Kajian khusus tentang fiqih untuk muslimah",
    date: "2024-09-23",
    time: "09:00 - 11:00 WIB",
    location: "Masjid Utama Mufid",
    category: "kajian",
    speaker: "Ustadzah Aisyah",
  },
  {
    id: "AG006",
    title: "Bakti Sosial Ramadhan",
    description: "Pembagian sembako untuk warga kurang mampu",
    date: "2024-09-25",
    time: "08:00 - 12:00 WIB",
    location: "Halaman Yayasan Mufid",
    category: "event",
  },
  {
    id: "AG007",
    title: "Kajian Kitab Tauhid",
    description: "Pembahasan kitab tauhid untuk pemula",
    date: "2024-09-27",
    time: "19:30 - 21:00 WIB",
    location: "Masjid Utama Mufid",
    category: "kajian",
    speaker: "Ustadz Muhammad Rizki",
  },
  {
    id: "AG008",
    title: "Santunan Anak Yatim",
    description: "Kegiatan santunan bulanan untuk anak yatim",
    date: "2024-09-28",
    time: "09:00 - 12:00 WIB",
    location: "Aula Utama",
    category: "event",
  },
]

// Kajian Sessions Data
export const kajianSessionsData: KajianSession[] = [
  {
    id: "KJ001",
    title: "Kajian Kitab Riyadhus Shalihin",
    description: "Pembahasan hadits-hadits pilihan tentang adab dan akhlak dalam Islam. Cocok untuk semua kalangan.",
    speaker: "Ustadz Ahmad Sulaiman, Lc., M.A.",
    schedule: "Setiap Sabtu",
    time: "19:30 - 21:00 WIB",
    location: "Masjid Utama Mufid",
    category: "rutin",
    kitab: "Riyadhus Shalihin",
    level: "menengah",
    registered: 85,
    capacity: 100,
    image: "bg-gradient-to-br from-red-500/20 to-rose-500/10",
  },
  {
    id: "KJ002",
    title: "Tahsin Al-Quran Dewasa",
    description: "Belajar membaca Al-Quran dengan tajwid yang benar. Fokus pada perbaikan makharijul huruf.",
    speaker: "Ustadz Ibrahim Hasan, Hafizh",
    schedule: "Senin & Kamis",
    time: "18:00 - 19:30 WIB",
    location: "Ruang TPA Lt. 1",
    category: "rutin",
    level: "pemula",
    registered: 28,
    capacity: 30,
    image: "bg-gradient-to-br from-rose-500/20 to-orange-500/10",
  },
  {
    id: "KJ003",
    title: "Kajian Fiqih Kontemporer",
    description: "Pembahasan masalah-masalah fiqih terkini sesuai dengan perkembangan zaman.",
    speaker: "Ustadz Dr. Muhammad Fauzi, M.Ag.",
    schedule: "Setiap Ahad",
    time: "08:00 - 10:00 WIB",
    location: "Aula Serbaguna",
    category: "rutin",
    level: "lanjutan",
    registered: 45,
    capacity: 60,
    image: "bg-gradient-to-br from-amber-500/20 to-orange-500/10",
  },
  {
    id: "KJ004",
    title: "Parenting Islami Online",
    description: "Kajian online tentang mendidik anak sesuai tuntunan Islam untuk orang tua muslim.",
    speaker: "Ustadzah Fatimah Az-Zahra, S.Pd.I",
    schedule: "Setiap Rabu",
    time: "20:00 - 21:30 WIB",
    location: "Online via Zoom",
    category: "online",
    level: "menengah",
    registered: 120,
    capacity: 200,
    image: "bg-gradient-to-br from-orange-500/20 to-red-500/10",
  },
  {
    id: "KJ005",
    title: "Tafsir Al-Quran",
    description: "Pembahasan tafsir ayat-ayat Al-Quran secara mendalam dengan pendekatan ilmiah.",
    speaker: "Ustadz Ahmad Sulaiman, Lc., M.A.",
    schedule: "Setiap Selasa",
    time: "19:30 - 21:00 WIB",
    location: "Masjid Utama Mufid",
    category: "rutin",
    kitab: "Tafsir Ibnu Katsir",
    level: "lanjutan",
    registered: 65,
    capacity: 80,
    image: "bg-gradient-to-br from-red-500/20 to-amber-500/10",
  },
  {
    id: "KJ006",
    title: "Kajian Akhlaq untuk Remaja",
    description: "Kajian khusus remaja tentang akhlaq dan adab dalam kehidupan sehari-hari.",
    speaker: "Ustadz Muhammad Rizki, S.Ag.",
    schedule: "Setiap Jumat",
    time: "16:00 - 17:30 WIB",
    location: "Ruang Remaja Lt. 2",
    category: "rutin",
    level: "pemula",
    registered: 35,
    capacity: 40,
    image: "bg-gradient-to-br from-rose-500/20 to-pink-500/10",
  },
  {
    id: "KJ007",
    title: "Workshop Hafalan Al-Quran",
    description: "Workshop intensif metode menghafal Al-Quran dengan teknik yang efektif.",
    speaker: "Ustadz Ibrahim Hasan, Hafizh",
    schedule: "Sabtu, 28 Sept 2024",
    time: "08:00 - 12:00 WIB",
    location: "Aula Utama",
    category: "khusus",
    level: "menengah",
    registered: 40,
    capacity: 50,
    image: "bg-gradient-to-br from-amber-500/20 to-red-500/10",
  },
  {
    id: "KJ008",
    title: "Kajian Hadits Arba'in",
    description: "Pembahasan 40 hadits pilihan Imam Nawawi dengan penjelasan yang komprehensif.",
    speaker: "Ustadz Dr. Ahmad Fauzi, M.Ag.",
    schedule: "Setiap Kamis",
    time: "19:30 - 21:00 WIB",
    location: "Masjid Utama Mufid",
    category: "rutin",
    kitab: "Al-Arba'in An-Nawawiyyah",
    level: "menengah",
    registered: 55,
    capacity: 70,
    image: "bg-gradient-to-br from-orange-500/20 to-rose-500/10",
  },
]
